### ISSUE TITLE
can't install with composer with php 5.6 and latest version of guzzle

### ISSUE THREAD

**Issue by sl-fedegiust** [dnetix/redirection#1]
I'm trying to install this via composer but getting an error.
I'm using php 5.6 and guzzle 6

**Comment by dnetix** [comment]
Hello @sl-fedegiust, I already had that problem, and I resolved it for the release version 0.3.5, please update to that one. On that version this library works even for PHP 5.4

**Comment by sl-fedegiust** [comment]
@dnetix 

I just tried

```
$ composer require dnetix/redirection:0.3.5
```

But it's still giving me this error 

![image](https://cloud.githubusercontent.com/assets/13888424/23993795/c7b0eed0-0a20-11e7-8503-e8d9fd04938b.png)

Same with your 0.3.6 version.
Will it work with guzzle 6? On your composer.json you are declaring version ^5.3 (above 5.3 and below 6) [https://getcomposer.org/doc/articles/versions.md#caret](url)

**Comment by dnetix** [comment]
Hello @sl-fedegiust which parameter have you set on the minimum-stability setting? I'm always interested on make this library as better as I can, so if in your fork you make changes that can help me with it, they are more than welcome.

I'm just checked with the VM that I have with PHP 5.4 and it worked just fine
![image](https://cloud.githubusercontent.com/assets/4644865/24067977/d3f8d842-0b51-11e7-93a3-6f728b120d44.png)

**Comment by dnetix** [comment]
Since the version 0.4.1+ there will be no problem with Guzzle because it works from the version 5.3 to 6.2.
