### ISSUE TITLE
Trankey o SecretKey?

### ISSUE THREAD

**Issue by lauana-oh** [dnetix/redirection#17]
Hola Diego, quiero comentarte un punto que me causó confusión y de pronto podría pasar con otra persona. 

En la utilización de la librería tenemos la siguiente estructura:
$placetopay = new Dnetix\Redirection\PlacetoPay([
    'login' => 'YOUR_LOGIN',
    'tranKey' => 'YOUR_TRANKEY',
...
    ]
]);

Pero en el https://dev.placetopay.com/web/redirection/, dice que la trankey sería:
$tranKey = base64_encode(sha1($nonce . $seed . $secretKey, true));

Después de algunos intentos fallidos, descubrí que lo que tenía que poner en esa librería era la que en el sitio se llama secretKey. De pronto, se podría adicionar una nota en la documentación o actualizar el website para evitar futuras confusiones. Me cuentas si estoy en lo correcto o no.

Desde ya, muchas gracias por tu atención

**Comment by Xfirepc** [comment]
Tengo la misma confusión como @lau-hubler , debería generarse una transaccional key antes de hacer el post en _api/session_ Actualmente la estructura genera un problema con la Autenticación espero estar en lo correcto.
Saludos!

**Comment by dnetix** [comment]
Estas en lo correcto, pero lo mejor sería cambiar la documentación para que se entienda mejor el concepto porque ya es conocida por los que la usan y cambiar ese parametro haría que se tenga que cambiar las implementaciones actuales
