### ISSUE TITLE
Typed property Dnetix\Redirection\Entities\NameValuePair::$value must be string, array used

### ISSUE THREAD

**Issue by rickfleen** [dnetix/redirection#26]
File: dnetix/redirection/src/Traits/LoaderTrait.php

When check an Id of an approved payment

 $response = placetopay()->query($requestId);

Some of debug:
Dnetix\Redirection\Contracts\Entity::load(['keyword' => 'credit', 'value' => ['code' => 1, 'type' => '00', 'groupCode' => 'C', 'installments' => 1], 'displayOn' => 'none'], ['keyword', 'value', 'displayOn'])

Regards

**Comment by dnetix** [comment]
You're completely right about it, thanks for the feedback, Im working on it right now
