### ISSUE TITLE
problemas con la generacion del trankey

### ISSUE THREAD

**Issue by andresp406** [dnetix/redirection#29]
Hola diego

te escribo por que al momento de la integracion con la api me esta arrojando un error 401 Unauthorized` response: (truncated...) 
he realizado el seed el nonce y el trankey como dice la documentacion pero aun asi sigue saliendo ese error

**Comment by dnetix** [comment]
Hola Andres

Como que has generado el nonce y el trankey? No entiendo esa parte, viniendo de un issue de esta librería, acá se generan automáticamente, solo necesitas poner el login y trankey que te asignan en PlacetoPay y el SDK se encarga del resto

**Comment by andresp406** [comment]
Hola Diego

si es que estaba haciendo el proceso manual con GuzzleHttp y se me complica un poco al momento de sacar el nonce y el trankey, pero viendo el readme de este paquete ya entiendo como es el proceso, te agradezco mucho el feedback.

saludos cordiales
