### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by sl-josealsina** [dnetix/redirection#4]
Hello,
I get the following error when trying to install using the command 
composer require dnetix/redirection
<<
  Problem 1
    - The requested package dnetix/redirection No version set (parsed as 1.0.0)
is satisfiable by dnetix/redirection[No version set (parsed as 1.0.0)] but these
 conflict with your requirements or minimum-stability.
>>

**Comment by dnetix** [comment]
Hello, that's a weird problem, I just tried and it work, maybe share your composer.json in order to check if there is some conflict.

**Comment by dnetix** [comment]
Could you fix this problem?

**Comment by sl-josealsina** [comment]
Not really. I downloaded the code and run as is, but I get the above error

**Comment by Slayers20** [comment]
Have you find a solution?
