### ISSUE TITLE
Problem - using postman

### ISSUE THREAD

**Issue by sl-josealsina** [dnetix/redirection#5]
Hello,

I have followed your example using json and when trying to send a request I get the following error.  Any ideas?
{
    "status": {
        "reason": 0,
        "status": "FAILED",
        "message": "file_put_contents(/var/www/vhosts/dev.placetopay.com/sites/redirection/storage/logs/request.log): failed to open stream: Permission denied",
        "date": "2017-06-16T17:04:56-05:00"
    }
}

**Comment by dnetix** [comment]
Can you try again please, I was just updating the development version.

**Comment by sl-josealsina** [comment]
It is working as expected. Thank you
