### ISSUE TITLE
The transaction has been declined

### ISSUE THREAD

**Issue by sl-josealsina** [dnetix/redirection#6]
Hello,

I am using one of your test credit cards but I get the following
Date 2017-06-23 13:07:47
Amount COP $2,000
Authorization 000000
Receipt 1498241268
Account 
IP address 212.139.84.16
State Rejected
Response Code XL

My reference details are
Reference
TEST-SL-123456
Description
Testing Payment
Date
2017-06-23 13:06:49
Session
479

Any ideas as to why it does not work? I do not see the response code XL in your documentation

**Comment by dnetix** [comment]
Hello Jose
Response code are kind of a legacy value sustained for older integrations of another system that its being replaced, I advise you not to rely your code on them, they are for information purposes when needed and can change along with the gateway that respond them (Credit Card Providers and others).
Please handle the response according to the **status** that can be APPROVED, REJECTED, PENDING, FAILED and handle the logic accordingly.

Keep in mind that exists two kind of status, Session and Transaction ones. one session groups zero or many transactions a session can be APPROVED with two transactions one REJECTED and another APPROVED, and if you use the partial payments feature you can have many transactions APPROVED but the session state can be APPROVED_PARTIAL if there is still remaining amount to pay.

This is a possible response for the getRequestInformation

```
{
  "requestId": 4,
  "status": {
    "status": "APPROVED_PARTIAL",
    "reason": "P0",
    "message": "La petición está parcialmente aprobada",
    "date": "2017-06-27T12:03:39-05:00"
  },
  "request": {
    "locale": "es_CO",
    "payer": {
      "document": "1040035000",
      "documentType": "CC",
      "name": "Carmen",
      "surname": "Cronin",
      "email": "dcallem88@msn.com",
      "mobile": "3006108300"
    },
    "buyer": {
      "document": "1040035000",
      "documentType": "CC",
      "name": "Carmen",
      "surname": "Cronin",
      "email": "dcallem88@msn.com",
      "mobile": 3006108300
    },
    "payment": {
      "reference": "TEST_20170627_170305",
      "description": "Itaque quia omnis ducimus.",
      "amount": {
        "currency": "COP",
        "total": 158000
      },
      "allowPartial": true
    },
    "returnUrl": "http://dnetix.dev/p2p/client",
    "ipAddress": "127.0.0.1",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36",
    "expiration": "2017-06-28T17:03:05+00:00",
    "captureAddress": false,
    "skipResult": false,
    "noBuyerFill": false
  },
  "payment": [
    {
      "status": {
        "status": "APPROVED",
        "reason": "00",
        "message": "Aprobada",
        "date": "2017-06-27T12:03:33-05:00"
      },
      "internalReference": 1448487817,
      "paymentMethod": "card",
      "paymentMethodName": "Visa",
      "issuerName": "BANCO DE PRUEBAS",
      "amount": {
        "from": {
          "currency": "COP",
          "total": 20000
        },
        "to": {
          "currency": "COP",
          "total": 20000
        },
        "factor": 1
      },
      "authorization": "000000",
      "reference": "TEST_20170627_170305",
      "receipt": "1498583013",
      "franchise": "CR_VS",
      "refunded": false,
      "processorFields": [
        {
          "keyword": "lastDigits",
          "value": "****1111",
          "displayOn": "none"
        },
        {
          "keyword": "id",
          "value": "58d53ca56a38535a2fac07db954d5b35",
          "displayOn": "none"
        }
      ]
    }
  ]
}
```
As you can see the first level status refers to the session state and the individual ones for the payment transactions (is an array) is the status for each transaction.
