### ISSUE TITLE
Uncaught Error: Class 'Dnetix\Redirection\PlacetoPay'

### ISSUE THREAD

**Issue by josuerod7** [dnetix/redirection#8]
Hi, i have this problem!! HELP Me!!

Problem 1
- The requested package dnetix/redirection No version set (parsed as 1.0.0)
is satisfiable by dnetix/redirection[No version set (parsed as 1.0.0)] but these
conflict with your requirements or minimum-stability.

**Comment by dnetix** [comment]
I think that the error in your case was that the version does not started on 1.0.0 but was on the 0.6.x so I just released a new version 1.0.0 with dispersion support, try it out.
