### ISSUE TITLE
string(30) "No service URL provided to use"

### ISSUE THREAD

**Issue by yosefgranados** [dnetix/redirection#9]
Buenas tardes, al momento de correr los ejemplos se despliega esta información. No he podido conectarme a la plataforma, tengo los valores del login, trankey y url pero se despliega ese aviso.

**Comment by dnetix** [comment]
Hola Yosef, puedes enviarme una copia de como estas cargando la librería.

**Comment by dnetix** [comment]
Este mensaje solo ocurre cuando la librería no se inicializa con el parametro "url" como lo menciona el README

```
$placetopay = new Dnetix\Redirection\PlacetoPay([
    'login' => 'YOUR_LOGIN',
    'tranKey' => 'YOUR_TRANKEY',
    'url' => 'https://THE_BASE_URL_TO_POINT_AT',
]);
```
